import { balanceV1, type BalanceV1 } from '../data/economy/balanceV1'
import { grantCommandEnergy, resolveCommandEnergyRegen, spendCommandEnergy } from '../domain/meta/CommandEnergy'
import type { CommandEnergyState } from '../domain/meta/MetaState'

export type SimulationScenario = 'casual' | 'regular' | 'active'
export type SimulationPeriodDays = 1 | 7 | 30
export type SimulationResult = Readonly<Record<string, unknown>> & { scenario: SimulationScenario; days: SimulationPeriodDays; speed: 1 | 3; waves: number; wavesStarted: number; wavesBlockedByEnergy: number; commandEnergyRemaining: number; binhPhuAcquired: number; binhPhuUsed: number; smallBinhPhuAcquired: number; smallBinhPhuUsed: number; mediumBinhPhuAcquired: number; mediumBinhPhuUsed: number; largeBinhPhuAcquired: number; largeBinhPhuUsed: number; gold: number; goldEarned: number; goldEarnedFromGameplay: number; goldReturnedFromGacha: number; goldSpent: number; goldRemaining: number; knb: number; knbEarned: number; knbSpent: number; knbRemaining: number; gachaPulls: number; goldGachaOutcomes: Readonly<Record<string, number>>; weaponAcquired: number; gemAcquired: number; highestWeaponLevel: number; highestGemLevel: number; highestEquipmentLevel: number; equipmentInstancesRemaining: number; recruitmentPulls: number; ownedHeroes: number; ownedHeroCount: number; duplicateShards: number; remainingHeroShards: Readonly<Record<string, number>>; stars: number; twoStarHeroes: number; threeStarHeroes: number; fourStarHeroes: number; fiveStarHeroes: number; anhHon: number; anhHonEarned: number; anhHonSpent: number; anhHonRemaining: number; evolutionProgress: string }
type EquipmentTable = { slot: 'weapon' | 'gem'; levels: Readonly<Record<number, Readonly<Record<string, number>>>> }
const fallbackMinutes: Record<SimulationScenario, number> = { casual: 30, regular: 60, active: 120 }
function seeded(seed: number): () => number { let state = seed >>> 0; return () => { state = (state * 1664525 + 1013904223) >>> 0; return state / 0x1_0000_0000 } }
function weightedKey(weights: Readonly<Record<string, number>>, random: () => number): string { const entries = Object.entries(weights); const total = entries.reduce((sum, [, weight]) => sum + weight, 0); if (!(total > 0)) throw new Error('Simulation weighted pool is empty'); let cursor = random() * total; for (const [key, weight] of entries) { cursor -= weight; if (cursor < 0) return key } return entries[entries.length - 1][0] }
function mergeEquipment(counts: Map<string, Map<number, number>>, config: BalanceV1) { const tables = config.equipment.tables as Readonly<Record<string, EquipmentTable>>; let highestWeaponLevel = 0; let highestGemLevel = 0; for (const [id, levels] of counts) { const table = tables[id]; if (!table) continue; for (let level = 1; level < config.equipment.levelCount; level += 1) { const count = levels.get(level) ?? 0; if (count >= config.equipment.mergeInputs) { const promoted = Math.floor(count / config.equipment.mergeInputs); levels.set(level, count % config.equipment.mergeInputs); levels.set(level + 1, (levels.get(level + 1) ?? 0) + promoted) } } for (const [level, count] of levels) if (count > 0) { if (table.slot === 'weapon') highestWeaponLevel = Math.max(highestWeaponLevel, level); else highestGemLevel = Math.max(highestGemLevel, level) } } const countSlot = (slot: 'weapon' | 'gem') => [...counts].reduce((sum, [id, levels]) => sum + (tables[id]?.slot === slot ? [...levels.values()].reduce((a, b) => a + b, 0) : 0), 0); const weapon = countSlot('weapon'); const gem = countSlot('gem'); return { total: weapon + gem, highestWeaponLevel, highestGemLevel, highest: Math.max(highestWeaponLevel, highestGemLevel) } }

export function simulateEconomy(scenario: SimulationScenario, days: SimulationPeriodDays, seed = 1, config: BalanceV1 = balanceV1, speed: 1 | 3 = 1): SimulationResult {
  if (!Number.isSafeInteger(seed) || seed < 0) throw new Error('Simulation seed must be a non-negative safe integer')
  const random = seeded(seed); const minutes = (config.simulation.minutesPerDay[scenario] ?? fallbackMinutes[scenario]) * days; const plannedWaves = Math.floor(minutes * config.simulation.wavesPerHour / 60); const enemyTable = config.rewardSources.enemyKillGold as Readonly<Record<string, number>>; const enemyIds = Object.keys(enemyTable); const stageReward = config.rewardSources.stageClear.prototypeStage; const energyConfig = { baseCap: config.commandEnergy.cap, regenIntervalMs: config.commandEnergy.regenIntervalMs }; let energyState: CommandEnergyState = { current: config.commandEnergy.cap, regenAnchorAtMs: 0 }; let wavesStarted = 0; let wavesBlockedByEnergy = 0; let gold = 0; let goldEarnedFromGameplay = 0; let goldReturnedFromGacha = 0; let gachaPulls = 0; const outcomes: Record<string, number> = {}; const equipment = new Map<string, Map<number, number>>(); let smallAcquired = 0; let mediumAcquired = 0; let largeAcquired = 0; let smallUsed = 0; let mediumUsed = 0; let largeUsed = 0
  const addEquipment = (id: string) => { const levels = equipment.get(id) ?? new Map<number, number>(); levels.set(1, (levels.get(1) ?? 0) + 1); equipment.set(id, levels) }
  const runGacha = () => { while (gold >= config.gold.gachaPullCost) { gold -= config.gold.gachaPullCost; gachaPulls += 1; const outcome = weightedKey(config.gacha.weights, random); outcomes[outcome] = (outcomes[outcome] ?? 0) + 1; if (outcome === 'gold') { gold += config.gacha.goldReturn; goldReturnedFromGacha += config.gacha.goldReturn } else if (outcome === 'weapon') addEquipment('green-dragon-blade'); else if (outcome === 'gem') addEquipment('swift-jade'); else if (outcome === 'smallBinhPhu') smallAcquired += 1; else if (outcome === 'mediumBinhPhu') mediumAcquired += 1; else if (outcome === 'largeBinhPhu') largeAcquired += 1 } }
  const waveInterval = Math.max(1, Math.floor(3_600_000 / config.simulation.wavesPerHour)); const killGoldPerWave = Array.from({ length: config.simulation.enemiesPerWave }, (_, index) => enemyTable[enemyIds[index % Math.max(1, enemyIds.length)]] ?? 0).reduce((sum, value) => sum + value, 0)
  for (let wave = 0; wave < plannedWaves; wave += 1) { const nowMs = (wave + 1) * waveInterval; const resolved = resolveCommandEnergyRegen(energyState, nowMs, energyConfig); if (resolved.status === 'invalid-clock') { wavesBlockedByEnergy += 1; continue } energyState = resolved.state; let spent = spendCommandEnergy(energyState, config.commandEnergy.waveCost, nowMs, energyConfig); if (spent.status === 'insufficient') { for (const [kind, amount] of [['small', config.commandEnergy.binhPhu.small], ['medium', config.commandEnergy.binhPhu.medium], ['large', config.commandEnergy.binhPhu.large]] as const) { const available = kind === 'small' ? smallAcquired - smallUsed : kind === 'medium' ? mediumAcquired - mediumUsed : largeAcquired - largeUsed; if (available > 0) { const granted = grantCommandEnergy(energyState, amount, nowMs, energyConfig); if (granted.status === 'granted') { energyState = granted.state; if (kind === 'small') smallUsed += 1; else if (kind === 'medium') mediumUsed += 1; else largeUsed += 1; spent = spendCommandEnergy(energyState, config.commandEnergy.waveCost, nowMs, energyConfig); break } } } } if (spent.status !== 'spent') { wavesBlockedByEnergy += 1; continue } energyState = spent.state; wavesStarted += 1; gold += killGoldPerWave; goldEarnedFromGameplay += killGoldPerWave; if (wavesStarted % 10 === 0) gold += stageReward.gold; if (wavesStarted % 10 === 0) goldEarnedFromGameplay += stageReward.gold; runGacha() }
  const stageClears = Math.floor(wavesStarted / 10); const knbEarned = Math.floor(minutes * 60_000 / config.activePlay.intervalMs) * config.activePlay.knbPerInterval + stageClears * stageReward.knb; const anhHonEarned = stageClears * (stageReward.anhHon ?? 0); const owned = new Set<string>(config.simulation.startingHeroIds); const shards: Record<string, number> = {}; const recruitmentPulls = Math.floor(knbEarned / config.knbShop.chieuHienLenh); for (let i = 0; i < recruitmentPulls; i += 1) { const hero = weightedKey(config.recruitment.weights, random); if (owned.has(hero)) { const id = `shard_hero_${hero}`; shards[id] = (shards[id] ?? 0) + config.recruitment.duplicateShards } else owned.add(hero) }
  const starsByHero = new Map<string, number>([...owned].map((id) => [id, 1])); for (const heroId of owned) { const id = `shard_hero_${heroId}`; let star = 1; let count = shards[id] ?? 0; while (star < config.stars.max) { const required = config.stars.shardCosts[(star + 1) as 2 | 3 | 4 | 5]; if (count < required) break; count -= required; star += 1 } starsByHero.set(heroId, star); shards[id] = count }
  const costs = [config.evolution.anhHonCosts.rebirth, config.evolution.anhHonCosts.reincarnation, config.evolution.anhHonCosts.legendary]; let anhHonSpent = 0; let evolved = 0; const maxReady = Math.min(3, Math.floor(days / config.simulation.level100Readiness.daysPerStage)); for (let i = 0; i < maxReady; i += 1) { const cost = costs[i]; if (anhHonEarned - anhHonSpent < cost) break; anhHonSpent += cost; evolved += 1 }
  const equipmentSummary = mergeEquipment(equipment, config); const goldSpent = gachaPulls * config.gold.gachaPullCost; const knbSpent = recruitmentPulls * config.knbShop.chieuHienLenh; const distribution = [2, 3, 4, 5].map((star) => [...starsByHero.values()].filter((value) => value === star).length); const stars = [...starsByHero.values()].reduce((sum, value) => sum + value, 0); const binhPhuAcquired = smallAcquired + mediumAcquired + largeAcquired; const binhPhuUsed = smallUsed + mediumUsed + largeUsed
  return { scenario, days, speed, waves: plannedWaves, wavesStarted, wavesBlockedByEnergy, commandEnergyRemaining: energyState.current, binhPhuAcquired, binhPhuUsed, smallBinhPhuAcquired: smallAcquired, smallBinhPhuUsed: smallUsed, mediumBinhPhuAcquired: mediumAcquired, mediumBinhPhuUsed: mediumUsed, largeBinhPhuAcquired: largeAcquired, largeBinhPhuUsed: largeUsed, gold: gold, goldEarned: goldEarnedFromGameplay + goldReturnedFromGacha, goldEarnedFromGameplay, goldReturnedFromGacha, goldSpent, goldRemaining: gold, knb: knbEarned - knbSpent, knbEarned, knbSpent, knbRemaining: knbEarned - knbSpent, gachaPulls, goldGachaOutcomes: outcomes, weaponAcquired: outcomes.weapon ?? 0, gemAcquired: outcomes.gem ?? 0, highestWeaponLevel: equipmentSummary.highestWeaponLevel, highestGemLevel: equipmentSummary.highestGemLevel, highestEquipmentLevel: equipmentSummary.highest, equipmentInstancesRemaining: equipmentSummary.total, recruitmentPulls, ownedHeroes: owned.size, ownedHeroCount: owned.size, duplicateShards: Object.values(shards).reduce((sum, value) => sum + value, 0), remainingHeroShards: shards, stars, twoStarHeroes: distribution[0], threeStarHeroes: distribution[1], fourStarHeroes: distribution[2], fiveStarHeroes: distribution[3], anhHon: anhHonEarned - anhHonSpent, anhHonEarned, anhHonSpent, anhHonRemaining: anhHonEarned - anhHonSpent, evolutionProgress: evolved > 0 ? `stage-${evolved}` : 'normal' }
}
export function simulateMatrix(seed = 1, config: BalanceV1 = balanceV1): readonly SimulationResult[] { return (['casual', 'regular', 'active'] as const).flatMap((scenario) => ([1, 7, 30] as const).map((days) => simulateEconomy(scenario, days, seed, config))) }
export function goldGachaExpectedReturn(config: BalanceV1 = balanceV1): number { const total = Object.values(config.gacha.weights).reduce((sum, value) => sum + value, 0); return config.gacha.goldReturn * config.gacha.weights.gold / total }
