import { describe, expect, it } from 'vitest'
import { defaultBattleStage } from '../../src/data/campaign/haiBaTrungCampaign'
import { createWaveBeatGate, selectResultNarrative, selectWaveBeat, shouldShowPreBattleNarrative } from '../../src/ui/StageNarrative'
describe('GAME-C07 narrative selectors', () => {
  it('shows intro only for incomplete play and resolves beats', () => { expect(shouldShowPreBattleNarrative(false, defaultBattleStage.narrative)).toBe(true); expect(shouldShowPreBattleNarrative(true, defaultBattleStage.narrative)).toBe(false); expect(selectWaveBeat(defaultBattleStage.narrative, 1)).toBeTruthy(); expect(selectWaveBeat(defaultBattleStage.narrative, 2)).toBeUndefined() })
  it('matches App completion conversion semantics', () => { const progress = { completedStages: {} } as { completedStages: Record<string, number> }; expect(shouldShowPreBattleNarrative(Boolean(progress.completedStages[defaultBattleStage.id]), defaultBattleStage.narrative)).toBe(true); progress.completedStages[defaultBattleStage.id] = 1; expect(shouldShowPreBattleNarrative(Boolean(progress.completedStages[defaultBattleStage.id]), defaultBattleStage.narrative)).toBe(false) })
  it('selects safe victory and defeat copy', () => { expect(selectResultNarrative(defaultBattleStage.narrative, 'won')).toContain('chặn'); expect(selectResultNarrative(defaultBattleStage.narrative, 'lost')).toContain('vỡ') })
  it('gates beats to running waves and run identity', () => { const gate = createWaveBeatGate(); expect(gate('r1', 1, 'waiting', defaultBattleStage.narrative)).toBeUndefined(); expect(gate('r1', 1, 'running', defaultBattleStage.narrative)).toBeTruthy(); expect(gate('r1', 1, 'running', defaultBattleStage.narrative)).toBeUndefined(); expect(gate('r1', 6, 'running', defaultBattleStage.narrative)).toBeTruthy(); expect(gate('r1', 12, 'running', defaultBattleStage.narrative)).toBeTruthy(); expect(gate('r1', 18, 'running', defaultBattleStage.narrative)).toBeTruthy(); expect(gate('r1', 24, 'running', defaultBattleStage.narrative)).toBeTruthy(); expect(gate('r2', 1, 'running', defaultBattleStage.narrative)).toBeTruthy() })
})
